name: CI/CD Deployment to Surge.sh

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        run: surge ./ primer-parcial-electiva-2-MN.surge.sh --token ${{ secrets.SURGE_TOKEN }}